title: Minecraft Browser
email: njt1982@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  An easy item and recipe browser for Minecraft
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: TODO
#repository: ihd-hk/ihd-hk.github.io

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  enable_coderay: false
  parse_block_html: true
  math_engine: mathjax # Forced Default from GH Pages
plugins:
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
exclude:
  - assets/bootstrap
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed

# CANNOT CHANGE THESE
lsi: false
safe: true
source: ""
incremental: false
highlighter: rouge
gist:
  noscript: false
# kramdown:
#   math_engine: mathjax

